### ISSUE TITLE
Doesn't react to command or Alt + d when using WSL

### ISSUE THREAD

**Issue by FunctionDJ** [Jack89ita/vscode-open-file-from-path#15]
The plugin works in non-WSL environment, but simply doesn't show any life-signs when using WSL.

**Comment by kanlukasz** [comment]
Are you sure it still not working? Could you please show any step by step example?
How your dev environment looks like?

I tested it now and it seems to work fine.

My tests were done with WSL2 `Ubuntu 20.04`
And with VsCode `Version: 1.52.1 (system setup)`
And with ` Open file From Path 1.3.4`

**Comment by FunctionDJ** [comment]
It's been a while since i've created this issue. I don't have a setup currently to test it, but i can imagine it works now due to VSCode updates. I'll close this issue and when i bump into it again, i'll open it again or something =)
Thanks for getting back to it.
