### ISSUE TITLE
Ctrl + click shortcut

### ISSUE THREAD

**Issue by WebFactoryLtd** [Jack89ita/vscode-open-file-from-path#2]
Superb work! Excellent extension!

Question: any way to change _Alt + d_ to _Ctrl + click_?

**Comment by Jack89ita** [comment]
Hi!
That feature is not supported at the moment. I can try to add it when i have some free time.
Or if you want help me a PR is always welcomed.
Thanks!

**Comment by WebFactoryLtd** [comment]
I'll dig into it! Would really love to have something similar to ctrl+click :)

**Comment by Jack89ita** [comment]
Closed for inactivity.
