### ISSUE TITLE
Issue with Multi-root Workspaces?

### ISSUE THREAD

**Issue by ph-laugier** [Jack89ita/vscode-open-file-from-path#3]
I'm new to vscode, so I may be mistaken, but I have the impression your extension is not supporting multi-root workspaces. It only open the file if it is located below the first of the multiple roots.
Investigating a bit your code, it seems that the problem is in the usage of rootPath which is deprecated and also suppose a single root.

**Comment by Jack89ita** [comment]
Hi and thank you for your feedback!
To understand better your issue, can you make an example? Why would you open a file from a workspace to another?
What are you trying to accomplish?

**Comment by ph-laugier** [comment]
Hi Giacomo,

My workspace looks like this:
{
    "folders": [
        {
            "path": "aaa"
        },        {
            "path": "bbb"
        },        {
            "path": "ccc"
        }
    ]
}

Your extension only works for files located under "aaa".

**Comment by Jack89ita** [comment]
In this plugin there's a setting called "startingPath"; it can be a sequence of string separated by a comma. It will set the starting path to search to multiple workspace.
In your case you could try to set it to: "/aaa/,/bbb/,/ccc/".
Let me know if it works, in the meantime i'll try to update my code to work with multi-root.
Thanks!

**Comment by ph-laugier** [comment]
ok. Thanks

**Comment by Jack89ita** [comment]
Cosed for inactivity.
