### ISSUE TITLE
"Warning, no matches were found", even with existing files in relative path

### ISSUE THREAD

**Issue by llagerlof** [Jack89ita/vscode-open-file-from-path#4]
OS: Windows 8.1
vscode: 1.27.1
plugin: 1.2.4

I keep receiving the message "Warning, no matches were found" when I ALT+d in any of my included files.

**My scenario:**

The opened file: /project/module1/tool/script/myfile.php

**Inside it I have:**
```
require_once '../../../module2/class/MyClass.php';
```
The file MyClass.php exists in the given path and is sucefully included when I run the script myfile.php. But I continue receiving this plugin error when I try to open the file using ALT+d. 

Before the ALT-d, I tried click in any part of the string, tried select the file name, tried select the full relative path, nothing works.

I can provide more information if you need. Thanks!

**Comment by Jack89ita** [comment]
Thank you for the feedback! I will check the problem and let you know.
In the meantime if you want you can try to play with the setting `open-file-from-path.regExp` and try to find the best combinations that suits you!
Cheers!

**Comment by llagerlof** [comment]
After some extension debugging I think found the problem. Please, tell me if I missed something.

Inside the ```for (var index in files)``` loop the **filePathConverted** successfully received the full path of MyClass.php

The script never enter in this comparisson, let's see why:
```php
if ((matchFileName && filePathConverted.split('/').pop() == lastPart) || (!matchFileName && filePathConverted.indexOf(lastPart)>0)){
```
**matchFileName** is set to false, so only the ```filePathConverted.indexOf(lastPart)>0``` can save us.

**lastPart** currently has the relative path of the file name (../../../module2/class/MyClass.php), so ```indexOf()``` can't find it in **filePathConverted** since it contains the full path.

Note: I changed the open-file-from-path.matchFileName to true and worked, but this option can't be trusted because, you know, the extension can find other file with the same name.

**Comment by bladerunner2020** [comment]
I have similar issue. It cannot find path staring with  '../'

**Comment by Jack89ita** [comment]
Hello guys!
Thanks for the feedback and sorry for taking so long to solve this.
Try to update and if you still have the problem open a new issue.
