### ISSUE TITLE
different tabs

### ISSUE THREAD

**Issue by redalan** [Jack89ita/vscode-open-file-from-path#5]
Do not open in the same tab. Allow different files to be opened in different tabs.

**Comment by Jack89ita** [comment]
Hi! thank you for the feedback!
I think this is a good idea, but how would you manage this? with an option in the plugin settings?

**Comment by redalan** [comment]
I think it would be great if the files were opened in different tabs. That is, not on the same tab of the previous one. Many times it is necessary to edit referenced files simultaneously.

**Comment by redalan** [comment]
If you want to keep the current option to open all files in the same tab, you could put in the configuration: "open in different tabs"

**Comment by Jack89ita** [comment]
Hey @redalan, for me it is working as expected, infact when i try open file from a path, it'll open in a new tab.
There is a VS Code global configuration to open files in a new tabe, named
```"workbench.editor.enablePreview": false,```
What about using this?
I didn't find a way to force it in the API documentation.
Let me now what you think.
Thanks!

**Comment by redalan** [comment]
Ups! Sorry. I come from Dreamweaver and I did not know that option in Visual Code. I thought it was a component option. 🤦‍♂️ 
All good then.

By the way, thanks for the addon. 🤓

**Comment by Jack89ita** [comment]
No problem @redalan, thank you for using it!
